#!/usr/bin/env bash

# Copyright (c) 2016-2017 Bitnami
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ROOT_DIR=`cd "$( dirname "${BASH_SOURCE[0]}" )/.." >/dev/null && pwd`

# Check for some needed tools, install (some) if missing
which bats > /dev/null || {
   echo "ERROR: 'bats' is required to run these tests," \
        "install it from https://github.com/sstephenson/bats"
   exit 255
}

# Start a k8s cluster (minikube, dind) if not running
kubectl get nodes || {
    cluster_up=./script/cluster-up-minikube.sh
    ${cluster_up}
}

# Both RBAC'd dind and minikube seem to be missing rules to make kube-dns work properly
# add some (granted) broad ones:
kubectl get clusterrolebinding kube-dns-admin >& /dev/null || \
    kubectl create clusterrolebinding kube-dns-admin --serviceaccount=kube-system:default --clusterrole=cluster-admin

# Prep: load test library, save current k8s default context (and restore it at exit),
# as kubeless doesn't support --context
export TEST_CONTEXT=minikube
source script/libtest.bash
trap k8s_context_restore 0
k8s_context_save

# Run the tests thru bats:
kubectl create namespace kubeless
kubectl create -f https://github.com/kubeless/kubeless/releases/download/${KUBELESS_VERSION}/kubeless-${KUBELESS_VERSION}.yaml
kubectl rollout status -n kubeless deployment/kubeless-controller-manager

# Auto obtain list
# Ballerina
make -C ${ROOT_DIR}/stable/ballerina deploy
make -C ${ROOT_DIR}/stable/ballerina test
# .NET
make -C ${ROOT_DIR}/stable/dotnetcore deploy
make -C ${ROOT_DIR}/stable/dotnetcore test
# Go
make -C ${ROOT_DIR}/stable/golang deploy
make -C ${ROOT_DIR}/stable/golang test
# JAVA
make -C ${ROOT_DIR}/stable/java deploy
make -C ${ROOT_DIR}/stable/java test
# NodeJS
make -C ${ROOT_DIR}/stable/nodejs deploy
make -C ${ROOT_DIR}/stable/nodejs test
# PHP
make -C ${ROOT_DIR}/stable/php deploy
make -C ${ROOT_DIR}/stable/php test
make -C ${ROOT_DIR}/stable/php update
make -C ${ROOT_DIR}/stable/php update-verify
# Python
make -C ${ROOT_DIR}/stable/python deploy
make -C ${ROOT_DIR}/stable/python test
make -C ${ROOT_DIR}/stable/python update
make -C ${ROOT_DIR}/stable/python update-verify
# Ruby
make -C ${ROOT_DIR}/stable/ruby deploy
make -C ${ROOT_DIR}/stable/ruby test
# JVM
make -C ${ROOT_DIR}/incubator/jvm deploy
make -C ${ROOT_DIR}/incubator/jvm test


exit_code=$?

# Just showing remaining k8s objects
kubectl get all --all-namespaces

if [ ${exit_code} -ne 0 -o -n "${TRAVIS_DUMP_LOGS}" ]; then
    echo "INFO: Build ERRORed, dumping logs: ##"
    for ns in kubeless default; do
        echo "### LOGs: namespace: ${ns} ###"
        kubectl get pod -n ${ns} -oname|xargs -I@ sh -xc "kubectl logs -n ${ns} @|sed 's|^|@: |'"
    done
    echo "INFO: Description"
    kubectl describe pod -l created-by=kubeless
    echo "INFO: LOGs: pod: kube-dns ###"
    kubectl logs -n kube-system -l k8s-app=kube-dns -c kubedns
    echo "INFO: LOGs: END"
fi
[ ${exit_code} -eq 0 ] && echo "INFO: $0: SUCCESS" || echo "ERROR: $0: FAILED"
exit ${exit_code}
# vim: sw=4 ts=4 et si
