FROM python:3.8

RUN pip install --disable-pip-version-check --no-cache-dir \
      bottle==0.12.13 \
      cherrypy==8.9.1 \
      wsgi-request-logger \
      prometheus_client

WORKDIR /

ADD _kubeless.py .

USER 1000

ENV PYTHONUNBUFFERED 1

CMD ["python", "/_kubeless.py"]
