FROM bitnami/node:10

RUN apt-get update &&  apt-get install git

ADD lib/helper.js /kubeless_rt/lib/
ADD kubeless.js /kubeless_rt/
ADD package.json /kubeless_rt/
ADD kubeless-npm-install.sh /

WORKDIR /kubeless_rt/

RUN npm install -g pnpm \
  && pnpm install

USER 1000

CMD ["node", "kubeless.js"]
