FROM node:12

ADD helper.js /kubeless_rt/lib/
ADD kubeless.js /kubeless_rt/
ADD kubeless-npm-install.sh /

WORKDIR /kubeless_rt/

RUN npm install \
        body-parser@"^1.17.2" \
        express@"^4.15.3" \
        morgan@"^1.8.2" \
        prom-client@"^10.0.2" && \
    npm cache clean --force

USER 1000

CMD ["node", "kubeless.js"]
